# Generated by Django 5.0.4 on 2024-04-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0005_alter_itemparams_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzasizes',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='pizzasizes',
            name='slug',
            field=models.SlugField(blank=True, max_length=3, null=True, unique=True, verbose_name='URL'),
        ),
    ]
