# Generated by Django 5.0.4 on 2024-04-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0007_alter_itemparams_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaboard',
            name='price25',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для 25 см'),
        ),
        migrations.AlterField(
            model_name='pizzaboard',
            name='price32',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для 32 см'),
        ),
        migrations.AlterField(
            model_name='pizzaboard',
            name='price43',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена для 43 см'),
        ),
    ]
