# Generated by Django 5.0.4 on 2024-04-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0008_alter_pizzaboard_price25_alter_pizzaboard_price32_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizzaboard',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
