# Generated by Django 5.0.4 on 2024-04-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0009_pizzaboard_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafebranch',
            name='phone1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cafebranch',
            name='phone2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
