# Generated by Django 5.0.4 on 2024-04-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0010_cafebranch_phone1_cafebranch_phone2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaSauce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название соуса')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Соус для пиццы',
                'verbose_name_plural': 'Соус для пиццы',
                'db_table': 'pizza_sauces',
            },
        ),
    ]
