# Generated by Django 5.0.4 on 2024-04-18 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0011_pizzasauce'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название шапочки')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Шапочка для запеченных роллов',
                'verbose_name_plural': 'Шапочки для запеченных роллов',
                'db_table': 'toppings',
            },
        ),
        migrations.AlterModelOptions(
            name='pizzasauce',
            options={'verbose_name': 'Соус-основа пиццы', 'verbose_name_plural': 'Соус-основа пиццы'},
        ),
    ]
