# Generated by Django 5.0.4 on 2024-05-24 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0012_topping_alter_pizzasauce_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaAddons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название добавки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена в руб.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pizza_addons/', verbose_name='Изображение')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
            options={
                'verbose_name': 'Добавка для пиццы',
                'verbose_name_plural': 'Добавки для пиццы',
                'db_table': 'pizza_addons',
            },
        ),
        migrations.RemoveField(
            model_name='pizzaboard',
            name='price25',
        ),
        migrations.RemoveField(
            model_name='pizzaboard',
            name='price32',
        ),
        migrations.RemoveField(
            model_name='pizzaboard',
            name='price43',
        ),
        migrations.CreateModel(
            name='BoardParams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена в руб.')),
                ('board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_catalog.pizzaboard')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_catalog.pizzasizes', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Параметры борта',
                'verbose_name_plural': 'Параметры борта',
                'db_table': 'board_params',
            },
        ),
    ]
