# Generated by Django 5.0.4 on 2024-04-18 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0012_topping_alter_pizzasauce_options'),
        ('app_user', '0002_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='sauce_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_catalog.pizzasauce', verbose_name='Соус-основа'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='toppings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_catalog.topping', verbose_name='Шапочка'),
        ),
    ]
