# Generated by Django 5.0.4 on 2024-05-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_catalog', '0013_pizzaaddons_remove_pizzaboard_price25_and_more'),
        ('app_user', '0005_cartitem_pizza_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='addons',
            field=models.ManyToManyField(blank=True, to='app_catalog.pizzaaddons', verbose_name='Добавки к пицце'),
        ),
    ]
