# Generated by Django 5.0.4 on 2024-04-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0005_order_free_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='free_delivery',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость доставки'),
        ),
    ]
